### PR TITLE
Added list of streamers to readme using a re-runable script

### PR DESCRIPTION
**Pull request by tscholze**
Hi @csharpfritz,

my opinion, it would be great to see all participating Twitch streamers of the LiveCoders team.

That's why, and because I wanted to learn a little bit of Python, I created a simple script that uses the Twitch API to transform the requested JSON into a template-based markdown converter.

My Script: https://github.com/tscholze/python-twitch-teams-to-markdown-converter

This should fix issue #2 

Happy coding,

Tobi (tobonautilus from the chat)

### CODE REVIEW

**Comment by csharpfritz** [comment]
Nice!  Is there a way we can set this up to run regularly?

I think this could help us build out a team website with details that support and promote various live coders

**Comment by tscholze** [comment]
@csharpfritz 

I think there are more than one way to achieve an updating streamer table.

## Script
The Python script repository: 
https://github.com/tscholze/python-twitch-teams-to-markdown-converter

## General
First of all. I would add the "main" part of the `Readme.md` to the Template (`markdown-template.md`) of the Python script. That means with each run, the whole file will be re-generated aka updated.


## Azure Usecase?
Maybe we can use Azure for this? 
I have no deep Azure knowledge but some ideas. Would it be possible to implement such workflows like:

### Function / WebApp or App Center Pipeline? 
1. An Azure function will be triggered periocically every 15 min?)
2. The function checkouts the git repo 
3. Runs the script
4. Calls the script
5. Checks via `git status` if the file has been changed
6. If yes, commit and push the file back to the repository

### Hosted Azure VM or container
If we have a "real" linux we could use a cronjob to trigger the workflow from above. 
Another idea would be to implement a simple and repating Python `Timer` that performs the required steps.

## Topic for a stream?
What do you think? If you want to use Azure, it would be great to watch it via a live stream. :)

Greetings from Bavaria,
- Tobi

**Comment by csharpfritz** [comment]
Thinking about it, this could create a messy scenario with LOTS of commits
and updates to the README.

Let's talk about moving this functionality to a livecoders website.


Jeff

**Comment by tscholze** [comment]
@csharpfritz 
Okay! :) The website does not exist, yet? You tweeted today, that it would be great to have blog post for each live coder team member. Do you want to combine that in one (new) website for the Twitch team?

I think you would prefer a C# ASP.NET Core tech stack?

**Pull request merged**
